uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: agent_decode_in
        type: decode_in
      - initiator_responder: RESPONDER
        name: agent_decode_out
        type: decode_out
      analysis_components:
      - name: predictor
        parameters: []
        type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_decode_in.monitored_ap
        receiver: predictor.agent_decode_in_ae
        validate: 'True'
      - driver: predictor.scoreboard_ap
        receiver: scoreboard.expected_analysis_export
        validate: 'True'
      - driver: agent_decode_out.monitored_ap
        receiver: scoreboard.actual_analysis_export
        validate: 'True'
