comp_decode_in_if_pkg:
	vlog $(ECE748_PROJECT_HOME)/verification_ip/interface_packages/decode_in_pkg/src/decode_in_if.sv
comp_decode_in_pkg:
	vlog $(ECE748_PROJECT_HOME)/verification_ip/interface_packages/decode_in_pkg/decode_in_pkg.sv