uvmf:
  environments:
    control:
      agents:
      - initiator_responder: RESPONDER
        name: agent_control_in
        type: control_in
      - initiator_responder: RESPONDER
        name: agent_control_out
        type: control_out
      analysis_components:
      - name: predictor
        parameters: []
        type: control_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: control_out_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_control_in.monitored_ap
        receiver: predictor.agent_control_in_ae
        validate: 'True'
      - driver: predictor.scoreboard_ap
        receiver: scoreboard.expected_analysis_export
        validate: 'True'
      - driver: agent_control_out.monitored_ap
        receiver: scoreboard.actual_analysis_export
        validate: 'True'
