uvmf:
  environments:
    "decode" :
      imports:
        - { name: "lc3_prediction_pkg" }
        - { name: "decode_in_pkg" }
        - { name: "decode_out_pkg" }
      agents :
        - name: "decode_in_agent_inst" 
          type: "decode_in"
          initiator_responder: "INITIATOR"
        - name: "decode_out_agent_inst"
          type: "decode_out"
          initiator_responder: "RESPONDER"
      analysis_components :
        - name: "decode_predictor_inst"
          type: "decode_predictor"
      scoreboards : 
        - name: "decode_scoreboard_inst"
          sb_type: "uvmf_in_order_scoreboard"
          trans_type: "decode_out_transaction"
      tlm_connections :
        - driver:   "decode_in_agent_inst.monitored_ap"
          receiver: "decode_predictor_inst.predictor_ae"
        - driver:   "decode_predictor_inst.predictor_ap"
          receiver: "decode_scoreboard_inst.expected_analysis_export"
        - driver:   "decode_out_agent_inst.monitored_ap"
          receiver: "decode_scoreboard_inst.actual_analysis_export"
  util_components:
    "decode_predictor" :
      type: "predictor"
      analysis_exports:
      - name: "predictor_ae"
        type: decode_in_transaction
      analysis_ports:
      - name: "predictor_ap"
        type: decode_out_transaction